import type { GlossaryTerm } from "./types";

export const GLOSSARY: GlossaryTerm[] = [
  // -----------------------------------------------------------------------
  // Foundations
  // -----------------------------------------------------------------------
  {
    slug: "market",
    term: "Market",
    termHi: "बाज़ार",
    category: "foundations",
    short: "Any setup where buyers and sellers meet to agree on a price.",
    long: "A market is the social infrastructure that lets price emerge. It can be a Mumbai sabzi mandi, the NSE order book, a Telegram group selling phones, or a crude oil pit in Houston. The form changes; the function — discover a clearing price — does not.",
    related: ["price-discovery", "liquidity", "exchange", "otc"],
  },
  {
    slug: "price-discovery",
    term: "Price discovery",
    termHi: "मूल्य खोज",
    category: "foundations",
    short: "The process by which a market settles on a price through buying and selling activity.",
    long: "Price discovery is what happens when many people with different views about an asset bid and offer until someone trades. The trade is the verdict. Discovery is continuous; the price an asset trades at right now is the market's current best guess about its value.",
    related: ["bid-ask", "order-book", "market"],
  },
  {
    slug: "liquidity",
    term: "Liquidity",
    termHi: "तरलता",
    category: "foundations",
    short: "How easily you can buy or sell something without moving its price.",
    long: "Liquidity is depth, not just volume. Reliance trades crores worth every second — you can buy ₹10 lakh of it and barely move the price. A small-cap stock with the same daily volume might lurch 4% if you put in the same order. Liquidity matters most when you need to exit in a hurry.",
    related: ["bid-ask", "market-maker", "volume"],
    example: "On India VIX > 25 days, even Nifty 50 names see bid-ask spreads widen — liquidity dries up exactly when you want it most.",
  },
  {
    slug: "bid-ask",
    term: "Bid-ask spread",
    termHi: "बोली-पूछ अंतर",
    category: "foundations",
    short: "The gap between the highest price a buyer will pay (bid) and the lowest price a seller will accept (ask).",
    long: "If HDFC Bank shows bid ₹1,620.10 and ask ₹1,620.20, the spread is 10 paise. A market order to buy hits the ask; a market order to sell hits the bid. Spread is your cost just to enter and exit — invisible but real.",
    related: ["liquidity", "order-book", "market-order", "limit-order"],
  },
  {
    slug: "order-book",
    term: "Order book",
    category: "foundations",
    short: "The live, public list of all outstanding buy and sell orders for a security.",
    long: "Every limit order sits in the order book until it's filled or cancelled. The top of the book — best bid and best ask — is what most quote screens show. Below it is depth: how many shares are queued at each price level. Reading depth tells you whether a price is supported or about to break.",
    related: ["bid-ask", "limit-order", "market-maker"],
  },
  {
    slug: "exchange",
    term: "Exchange",
    termHi: "एक्सचेंज",
    category: "foundations",
    short: "A regulated venue where standardized contracts (stocks, futures) trade.",
    long: "Exchanges centralize liquidity, set rules, and guarantee settlement. NSE and BSE in India; NYSE and Nasdaq in the US; LSE in London. The opposite is OTC trading — bilateral deals away from any exchange (most bonds, forex, and derivatives trade OTC globally).",
    related: ["otc", "nse", "bse", "clearing"],
  },
  {
    slug: "otc",
    term: "OTC (Over-the-counter)",
    category: "foundations",
    short: "A trade negotiated bilaterally between two parties, not on an exchange.",
    long: "Most of the world's trading by value is OTC — bonds, currencies, swaps. The pricing is less transparent, but volumes are huge. Indian retail mostly never touches OTC; institutions do.",
    related: ["exchange", "forex"],
  },
  {
    slug: "limit-order",
    term: "Limit order",
    category: "foundations",
    short: "An order to buy or sell at a specified price or better.",
    long: "A limit buy at ₹1,615 for HDFC Bank only fills at ₹1,615 or lower; it might never fill. A limit sell at ₹1,620 sits until someone hits it. Limit orders let you control price; market orders let you control timing. You usually want limits.",
    related: ["market-order", "bid-ask", "order-book"],
  },
  {
    slug: "market-order",
    term: "Market order",
    category: "foundations",
    short: "An order to buy or sell immediately at the best available price.",
    long: "Market orders fill fast but at whatever the order book shows. In a thin stock or during a crash, you might fill far away from the last printed price. For Nifty 50 names in normal hours, the difference is negligible.",
    related: ["limit-order", "liquidity", "slippage"],
  },
  {
    slug: "slippage",
    term: "Slippage",
    category: "foundations",
    short: "The difference between the price you expected and the price you actually got.",
    long: "Slippage is the cost of needing liquidity right now. Higher in thin stocks, during news, and at open and close. Limit orders eliminate price slippage but introduce timing slippage (your order might not fill).",
    related: ["liquidity", "market-order"],
  },
  {
    slug: "market-maker",
    term: "Market maker",
    category: "foundations",
    short: "A firm that continuously quotes both buy and sell prices, earning the spread.",
    long: "Market makers provide liquidity for a fee — the bid-ask spread. They're not betting on direction; they're inventory managers earning a small edge on every round trip. In India, market making is concentrated in F&O; in the US, it's a much larger industry.",
    related: ["bid-ask", "liquidity"],
  },
  {
    slug: "broker",
    term: "Broker",
    termHi: "दलाल",
    category: "foundations",
    short: "An intermediary that routes your orders to an exchange.",
    long: "Zerodha, Groww, Upstox, ICICI Direct — these are brokers. They don't set the market price; they're a pipe. You pay them in brokerage (per-trade fee), DP charges, and sometimes spread markup on currency.",
    related: ["demat", "depository"],
    example: "Zerodha charges flat ₹20 per executed F&O order, ₹0 for equity delivery. Brokerage is a real cost — for active traders it compounds.",
  },
  {
    slug: "demat",
    term: "Demat account",
    category: "foundations",
    short: "An electronic account that holds your stocks and bonds.",
    long: "After dematerialization, Indian shares stopped being paper certificates. They live in your demat account at CDSL or NSDL, with a depository participant (your broker) as the interface. You can have one demat account per depository.",
    related: ["depository", "broker"],
  },
  {
    slug: "depository",
    term: "Depository (CDSL / NSDL)",
    category: "foundations",
    short: "The institution that holds shares electronically on behalf of investors.",
    long: "CDSL (Central Depository Services Ltd) and NSDL (National Securities Depository Ltd) are India's two depositories. They're the equivalent of bank vaults for shares. Your broker is your interface; the depository is where the shares actually 'live'.",
    related: ["demat", "broker"],
  },
  {
    slug: "clearing",
    term: "Clearing & settlement",
    category: "foundations",
    short: "The post-trade process that transfers money and shares between buyer and seller.",
    long: "When you 'buy' a stock today, you don't own it instantly. The trade is cleared by NSE Clearing or ICCL, and shares hit your demat on T+1 (one working day later). Most of the world runs on T+2; India is faster.",
    related: ["depository", "demat", "t-plus-1"],
  },
  {
    slug: "t-plus-1",
    term: "T+1 settlement",
    category: "foundations",
    short: "Trades on day T settle in your demat on the next working day.",
    long: "India moved fully to T+1 settlement in early 2023, ahead of the rest of the world. If you sell on Monday, money is in your account on Tuesday (less STT and charges). If you buy, shares hit your demat on Tuesday.",
    related: ["clearing", "stt"],
  },
  {
    slug: "nse",
    term: "NSE (National Stock Exchange)",
    category: "indian-equities",
    short: "India's largest exchange by volume, home of Nifty 50.",
    long: "Set up in 1992, NSE killed the open-outcry BSE trading floor by going fully electronic. Most equity volume in India is on NSE, especially in F&O. Headquartered in Mumbai.",
    related: ["bse", "nifty-50", "exchange"],
  },
  {
    slug: "bse",
    term: "BSE (Bombay Stock Exchange)",
    category: "indian-equities",
    short: "Asia's oldest exchange, home of the Sensex.",
    long: "Founded in 1875, BSE is the older of India's two main exchanges. It runs the Sensex (30 stocks) and has more listed companies than NSE, though daily volume is far lower.",
    related: ["nse", "sensex"],
  },
  {
    slug: "nifty-50",
    term: "Nifty 50",
    category: "indian-equities",
    short: "An index of India's 50 largest, most liquid stocks on the NSE.",
    long: "The Nifty 50 represents ~50-55% of total Indian market cap. Reliance, HDFC Bank, ICICI Bank, Infosys, and TCS together are usually around a third of the index. When people say 'the market is up 1%', they usually mean Nifty.",
    related: ["sensex", "nse", "index"],
  },
  {
    slug: "sensex",
    term: "Sensex (BSE Sensex)",
    category: "indian-equities",
    short: "BSE's flagship index of 30 large Indian companies.",
    long: "Older sibling of the Nifty. Most foreign coverage of India quotes Sensex; most domestic trading is tracked on Nifty. The two move within tenths of a percent of each other on any given day.",
    related: ["nifty-50", "bse"],
  },
  {
    slug: "bank-nifty",
    term: "Bank Nifty",
    category: "indian-equities",
    short: "NSE index of 12 large Indian banks; the most actively traded F&O index.",
    long: "Bank Nifty is the volatile, high-volume cousin of Nifty 50. Banks are leveraged to the macro economy — interest rates, NPAs, credit growth — so the index swings more. It's where most Indian options retail volume actually happens.",
    related: ["nifty-50", "fno"],
  },
  {
    slug: "index",
    term: "Index",
    termHi: "सूचकांक",
    category: "indian-equities",
    short: "A weighted basket of securities used to track a market or sector.",
    long: "Indices are tools, not portfolios. The Nifty 50 weights stocks by free-float market cap, so Reliance and HDFC Bank dominate its movement. Sectoral indices (Nifty IT, Nifty Pharma) let you see what's actually working without picking stocks.",
    related: ["nifty-50", "sensex", "market-cap"],
  },
  {
    slug: "market-cap",
    term: "Market capitalisation",
    termHi: "बाज़ार पूंजीकरण",
    category: "indian-equities",
    short: "The total value of a company's outstanding shares (price × shares outstanding).",
    long: "Reliance at ₹2,800 with ~676 crore shares has a market cap of about ₹19 lakh crore. Market cap is what the market thinks the whole company is worth right now. SEBI classifies large cap (top 100), mid cap (101-250), and small cap (251+) by ranking on market cap.",
    related: ["large-cap", "mid-cap", "small-cap"],
  },
  {
    slug: "large-cap",
    term: "Large cap",
    category: "indian-equities",
    short: "The top 100 Indian companies by market cap.",
    long: "Stable, well-followed, lower expected returns but lower drawdowns. Reliance, HDFC Bank, TCS, ICICI Bank, Infosys, ITC. SEBI's definition is rule-based and updates every six months.",
    related: ["mid-cap", "small-cap", "market-cap"],
  },
  {
    slug: "mid-cap",
    term: "Mid cap",
    category: "indian-equities",
    short: "Companies ranked 101 to 250 by market cap.",
    long: "Higher growth potential than large caps, but bigger drawdowns. Names like Tube Investments, Persistent Systems, Coforge, Page Industries. Many become large caps over a cycle; many also blow up.",
    related: ["large-cap", "small-cap"],
  },
  {
    slug: "small-cap",
    term: "Small cap",
    category: "indian-equities",
    short: "Companies ranked 251+ by market cap.",
    long: "Highest expected returns and highest risk. Many are illiquid — selling ₹5 lakh of a small cap can move the price 2%. Quality varies wildly. This is where retail loses the most money in bull market endings.",
    related: ["large-cap", "mid-cap", "liquidity"],
  },
  {
    slug: "pe-ratio",
    term: "P/E ratio (Price-to-Earnings)",
    category: "indian-equities",
    short: "How many years of current earnings the stock costs at today's price.",
    long: "If HDFC Bank earns ₹85/share and trades at ₹1,700, P/E is ~20. A P/E of 20 means you pay ₹20 of share price for every ₹1 of annual profit. High P/E = market expects fast growth (or is overpaying). Low P/E = pessimism or value (or a trap).",
    related: ["eps", "pb-ratio", "valuation"],
  },
  {
    slug: "eps",
    term: "EPS (Earnings per share)",
    category: "indian-equities",
    short: "Net profit divided by the number of shares outstanding.",
    long: "EPS is what each share 'earned' in profit. Quarterly EPS surprises move stocks — if the street expected ₹14 and the company delivered ₹17, that's a beat. Use trailing EPS for actual results, forward EPS for expectations.",
    related: ["pe-ratio"],
  },
  {
    slug: "pb-ratio",
    term: "P/B ratio (Price-to-Book)",
    category: "indian-equities",
    short: "Stock price divided by book value per share.",
    long: "Book value is shareholders' equity per share — what the company would theoretically be worth if liquidated. P/B is most useful for banks and asset-heavy companies. HDFC Bank trades around 3x P/B, PSU banks usually below 1x.",
    related: ["valuation", "pe-ratio"],
  },
  {
    slug: "dividend-yield",
    term: "Dividend yield",
    category: "indian-equities",
    short: "Annual dividend per share divided by current share price.",
    long: "ITC paying ₹13/share dividend at ₹450 share price = 2.9% yield. Indian indices yield less than 1.5% on average. Dividend yields under 2% don't help much during drawdowns; this isn't where Indian equity returns come from.",
    related: ["dividend"],
  },
  {
    slug: "valuation",
    term: "Valuation",
    category: "indian-equities",
    short: "An estimate of what a security is reasonably worth.",
    long: "Valuation is the bridge between price (what you pay) and value (what you get). Same stock can be expensive at one price and cheap a year later at the same price if earnings doubled. Common shortcuts: P/E, P/B, EV/EBITDA, DCF.",
    related: ["pe-ratio", "pb-ratio"],
  },
  {
    slug: "fii",
    term: "FII / FPI (Foreign Institutional Investor)",
    termHi: "विदेशी संस्थागत निवेशक",
    category: "indian-equities",
    short: "Overseas funds investing in Indian listed securities.",
    long: "FIIs (now formally FPIs) own roughly 18-20% of NSE listed market cap. When they buy, Nifty tends to rise and the rupee strengthens. When they sell — especially during global risk-off — Indian equities and the rupee both fall together. SEBI publishes daily FII flow data.",
    related: ["dii", "usd-inr", "risk-off"],
    example: "In October 2024 alone, FIIs sold ~₹1.14 lakh crore of Indian equities, the largest monthly outflow ever — Nifty fell ~6% the same month.",
  },
  {
    slug: "dii",
    term: "DII (Domestic Institutional Investor)",
    category: "indian-equities",
    short: "Indian mutual funds, insurance companies, and pension funds.",
    long: "DIIs have become India's structural buyer — thanks to monthly SIPs (~₹25,000 cr/month and rising), they buy steadily regardless of headlines. Over 2022-2024, DII buying largely offset FII selling. This dynamic has made Indian markets less FII-dependent than they were a decade ago.",
    related: ["fii", "sip"],
  },
  {
    slug: "sip",
    term: "SIP (Systematic Investment Plan)",
    category: "indian-equities",
    short: "Fixed-amount monthly investment into a mutual fund.",
    long: "India's most successful retail investment habit. ~₹25,000 crore flows in every month via SIPs. Doesn't time the market; averages your buy price over time. The base reason why DIIs can absorb FII selling.",
    related: ["dii"],
  },
  {
    slug: "fno",
    term: "F&O (Futures & Options)",
    category: "indian-equities",
    short: "Derivative contracts whose value comes from an underlying like Nifty.",
    long: "F&O lets you take leveraged positions — small margin controls large exposure. Indian F&O volume is among the largest in the world, mostly index options on Nifty and Bank Nifty. SEBI's own studies show ~90% of individual F&O traders lose money over a year.",
    related: ["futures", "options", "leverage"],
  },
  {
    slug: "futures",
    term: "Futures contract",
    category: "indian-equities",
    short: "An obligation to buy or sell an asset at a fixed price on a future date.",
    long: "Nifty futures with monthly expiry settle in cash on the last Thursday of the month. The price moves nearly tick-for-tick with spot Nifty. Futures are used for hedging and speculation; they're inherently leveraged via margin.",
    related: ["options", "fno", "leverage"],
  },
  {
    slug: "options",
    term: "Options contract",
    category: "indian-equities",
    short: "The right (not obligation) to buy or sell an asset at a fixed price.",
    long: "A call option lets you buy at a strike; a put lets you sell. Buyer pays premium; seller collects it but takes unlimited risk. Indian options market is dominated by weekly Bank Nifty and Nifty contracts. Most option buyers lose; most option sellers also lose during sharp moves.",
    related: ["futures", "fno", "premium"],
  },
  {
    slug: "leverage",
    term: "Leverage",
    termHi: "उत्तोलन",
    category: "risk",
    short: "Using borrowed money or derivatives to control more assets than your capital alone allows.",
    long: "₹1 lakh margin can control ₹10 lakh of Nifty futures — that's 10x leverage. Multiplies gains and losses equally. Margin calls force liquidation when leverage works against you. The single largest cause of retail blowups.",
    related: ["margin", "margin-call", "fno"],
  },
  {
    slug: "margin",
    term: "Margin",
    category: "risk",
    short: "Money you put up as collateral to take a leveraged position.",
    long: "SPAN + Exposure margin is what NSE requires to hold Nifty futures. Falls as a percentage of contract value during quiet markets, rises during volatile ones. If margin slips below maintenance level, your broker issues a margin call.",
    related: ["leverage", "margin-call"],
  },
  {
    slug: "margin-call",
    term: "Margin call",
    category: "risk",
    short: "A demand to add money to cover losses on a leveraged position.",
    long: "If you don't add funds, the broker liquidates your position at market price — often near the worst moment. Margin calls compound a market move: as prices fall, forced selling adds more pressure, which triggers more calls.",
    related: ["margin", "leverage"],
  },
  {
    slug: "circuit-breaker",
    term: "Circuit breaker / Price band",
    category: "risk",
    short: "Daily limits beyond which a stock or index pauses trading.",
    long: "Indian individual stocks have 2%, 5%, 10%, or 20% bands depending on category. Indices have 10%, 15%, 20% market-wide circuits that halt trading for cooling-off periods. Hit one and you can't exit — which is exactly when you most want to.",
    related: ["volatility"],
  },
  {
    slug: "volatility",
    term: "Volatility",
    termHi: "उतार-चढ़ाव",
    category: "risk",
    short: "How much an asset's price swings around in a given period.",
    long: "Annualised standard deviation of returns. Nifty's long-run vol is around 16-20%; a small cap can be 35-50%. Higher vol = bigger drawdowns possible, even if average return is similar. Vol is not direction.",
    related: ["india-vix", "drawdown"],
  },
  {
    slug: "india-vix",
    term: "India VIX",
    category: "risk",
    short: "Implied volatility of Nifty options over the next 30 days.",
    long: "When India VIX is sub-12, the market is sleepy. Spikes above 20 signal stress; above 25 is panic territory. Election day 2024, COVID March 2020, and demonetisation all printed VIX above 30. VIX usually moves opposite to Nifty.",
    related: ["volatility", "vix"],
  },
  {
    slug: "vix",
    term: "VIX (CBOE Volatility Index)",
    category: "risk",
    short: "The US equivalent of India VIX, derived from S&P 500 options.",
    long: "Known as 'the fear gauge'. Resting state is 12-15. Above 30 signals fear; above 40 is full panic. Spiked to 82 in March 2020 (COVID). VIX moves into India VIX with a lag — global fear bleeds in.",
    related: ["india-vix"],
  },
  {
    slug: "drawdown",
    term: "Drawdown",
    category: "risk",
    short: "The peak-to-trough decline of an investment.",
    long: "If Nifty falls from 26,000 to 23,400, that's a 10% drawdown. Maximum drawdown over a period tells you the worst loss you'd have stomached. Most retail investors quit during drawdowns — exactly when forward returns are highest.",
    related: ["volatility"],
  },
  {
    slug: "correlation",
    term: "Correlation",
    category: "risk",
    short: "How tightly two assets move together (-1 to +1).",
    long: "Nifty and S&P 500 correlate around 0.5 over years. In crises, correlations rise — everything sells off together, defeating naive diversification. Gold and equities are usually low/negative correlation; bonds and equities used to be, but became positive in 2022.",
    related: ["risk-off", "diversification"],
  },

  // -----------------------------------------------------------------------
  // Rates & money
  // -----------------------------------------------------------------------
  {
    slug: "interest-rate",
    term: "Interest rate",
    termHi: "ब्याज दर",
    category: "rates-and-money",
    short: "The price of borrowing money, expressed as a percentage per year.",
    long: "Every other rate in the economy is downstream of central bank policy rates. When the RBI hikes the repo, your home loan EMI rises and FD rates rise. When the Fed hikes in the US, the world's risk-free yield rises and money flows out of emerging markets like India.",
    related: ["repo-rate", "rbi", "yield", "inflation"],
  },
  {
    slug: "repo-rate",
    term: "Repo rate",
    termHi: "रेपो दर",
    category: "rates-and-money",
    short: "The rate at which the RBI lends overnight money to commercial banks.",
    long: "When the RBI cuts repo, banks borrow cheaper and can pass that on as cheaper loans. When it hikes, loans get expensive. Set every two months by the MPC. Currently the most-watched single number for the Indian economy. (As of late 2024, repo is 6.50%.)",
    related: ["rbi", "mpc", "reverse-repo"],
  },
  {
    slug: "reverse-repo",
    term: "Reverse repo rate",
    category: "rates-and-money",
    short: "The rate at which the RBI borrows from banks (parks their surplus money).",
    long: "Floors the short-term rate — banks won't lend in the market below what the RBI offers them. Sits about 25 bps below the repo rate. Important plumbing detail; less often headline news.",
    related: ["repo-rate", "rbi"],
  },
  {
    slug: "rbi",
    term: "RBI (Reserve Bank of India)",
    category: "rates-and-money",
    short: "India's central bank, in charge of monetary policy, banking regulation, and the rupee.",
    long: "Founded 1935. Sets the repo rate via the MPC, manages forex reserves (~$650 billion), supervises banks, regulates payments, and intervenes in USD/INR to control volatility. The single most powerful institution for Indian markets after the central government.",
    related: ["mpc", "repo-rate", "forex-reserves"],
  },
  {
    slug: "mpc",
    term: "MPC (Monetary Policy Committee)",
    category: "rates-and-money",
    short: "The six-member RBI committee that votes on the repo rate.",
    long: "Three RBI members (including the Governor) and three external economists. Meets every two months. The Governor's casting vote breaks ties. Inflation targeting framework: 4% ± 2% CPI.",
    related: ["rbi", "repo-rate"],
  },
  {
    slug: "fed",
    term: "Fed (Federal Reserve)",
    category: "rates-and-money",
    short: "The US central bank — sets the world's most important interest rate.",
    long: "When the Fed moves, every market globally has to adjust. Fed funds rate is the US equivalent of the repo rate. The dot plot and dot-by-dot 'guidance' often matter more than the actual rate move. Powell is currently chair.",
    related: ["fomc", "fed-funds-rate", "dxy"],
  },
  {
    slug: "fomc",
    term: "FOMC (Federal Open Market Committee)",
    category: "rates-and-money",
    short: "The Fed's policy committee that sets the US benchmark interest rate.",
    long: "Twelve members. Meets 8 times a year. Statement, presser, and 'dot plot' (rate projections) drive market moves. FOMC days are usually high-volatility for Nifty too, because USD strength/weakness flows through to emerging markets within hours.",
    related: ["fed", "fed-funds-rate"],
  },
  {
    slug: "fed-funds-rate",
    term: "Fed funds rate",
    category: "rates-and-money",
    short: "The overnight rate at which US banks lend reserves to each other.",
    long: "The Fed targets a range (e.g., 5.25-5.50%) and uses open-market operations to keep the rate there. The 'risk-free rate' for the world's reserve currency. When this is 5%+, EM equities have to compete with literally risk-free 5% yields — a huge headwind.",
    related: ["fed", "fomc"],
  },
  {
    slug: "inflation",
    term: "Inflation",
    termHi: "मुद्रास्फीति",
    category: "rates-and-money",
    short: "The rate at which prices generally rise — your money buys less each year.",
    long: "5% inflation means ₹100 today buys what ₹95 bought a year ago. Equity returns are nominal; real returns subtract inflation. Central banks try to keep inflation around a target (4% in India, 2% in the US) — too high and they hike, too low and they cut.",
    related: ["cpi", "real-return", "interest-rate"],
  },
  {
    slug: "cpi",
    term: "CPI (Consumer Price Index)",
    category: "rates-and-money",
    short: "The standard measure of price inflation faced by consumers.",
    long: "Indian CPI is heavily food-weighted (~46%) and is what the RBI targets. US CPI is the most-watched macro data point globally — releases move every major market simultaneously. Core CPI strips out food and energy for a cleaner trend signal.",
    related: ["inflation", "wpi", "core-cpi"],
  },
  {
    slug: "core-cpi",
    term: "Core CPI",
    category: "rates-and-money",
    short: "CPI excluding food and energy — the slower-moving inflation trend.",
    long: "Food and oil prices are volatile and largely outside policy control. Core CPI tells central banks whether inflation is broad-based or just a commodity shock. If core CPI rises while headline CPI falls, the Fed/RBI won't cut even if headline looks tame.",
    related: ["cpi", "inflation"],
  },
  {
    slug: "wpi",
    term: "WPI (Wholesale Price Index)",
    category: "rates-and-money",
    short: "Indian inflation at the wholesale producer level.",
    long: "WPI used to be the RBI's policy anchor; CPI replaced it in 2014. WPI is more sensitive to commodity prices and global supply. It leads CPI by a few months — when WPI spikes, CPI usually follows.",
    related: ["cpi", "inflation"],
  },
  {
    slug: "real-return",
    term: "Real return",
    category: "rates-and-money",
    short: "Return after subtracting inflation — your actual gain in purchasing power.",
    long: "An FD at 7% during 6% inflation gives you 1% real. Equity averaging 12% during 5% inflation gives you 7% real. Real returns are what compound your purchasing power; nominal returns are what your statement shows.",
    related: ["inflation", "nominal-return"],
  },
  {
    slug: "nominal-return",
    term: "Nominal return",
    category: "rates-and-money",
    short: "Return before adjusting for inflation — the headline number.",
    long: "If your portfolio is up 11% and inflation was 5%, the 11% is nominal. The 6% is real. Headlines and brochures almost always quote nominal returns.",
    related: ["real-return", "inflation"],
  },
  {
    slug: "yield",
    term: "Yield",
    termHi: "प्रतिफल",
    category: "bonds",
    short: "The annual return on a bond, expressed as a percentage of its current price.",
    long: "Bond yields move opposite to bond prices. The 10-year government bond yield is a key benchmark — it's what 'risk-free' looks like at long horizon. When yields rise, equity P/E multiples generally fall (rates compete with stocks for capital).",
    related: ["bond", "g-sec", "yield-curve"],
  },
  {
    slug: "yield-curve",
    term: "Yield curve",
    category: "bonds",
    short: "A chart of bond yields plotted against their maturities.",
    long: "Normally upward-sloping — longer maturity = higher yield (for taking on more risk). An inverted yield curve (short-term yields higher than long-term) has predicted every US recession in the past 60 years. The US 2s10s inverted in mid-2022 and stayed inverted into 2024.",
    related: ["yield", "us-10y", "recession"],
  },
  {
    slug: "us-10y",
    term: "US 10-year Treasury yield",
    category: "bonds",
    short: "The yield on the 10-year US government bond — the world's benchmark interest rate.",
    long: "Every long-duration asset in the world is priced relative to this. When the US 10Y rises from 3.5% to 4.5%, equity multiples globally compress. Real estate cap rates rise. Emerging market spreads widen. It's the single most important number for cross-asset thinking.",
    related: ["yield", "bond", "fed"],
  },
  {
    slug: "g-sec",
    term: "G-Sec (Government Security)",
    category: "bonds",
    short: "Bonds issued by the Government of India.",
    long: "G-Secs are the foundation of Indian fixed income. The 10-year G-Sec yield is what the RBI watches and what the rest of Indian credit is priced against. Retail can now buy via the RBI Retail Direct platform.",
    related: ["yield", "rbi"],
  },
  {
    slug: "t-bill",
    term: "T-Bill (Treasury Bill)",
    category: "bonds",
    short: "Short-dated government debt (91, 182, or 364 days).",
    long: "T-Bills are sold at a discount and redeemed at face value — the gap is your return. The 91-day T-Bill is the cleanest read on near-term rates in India. Returns are taxed as 'income from other sources'.",
    related: ["g-sec", "yield"],
  },
  {
    slug: "duration",
    term: "Duration",
    category: "bonds",
    short: "How sensitive a bond's price is to a change in yield.",
    long: "A 10-year bond with 8 years duration loses roughly 8% if yields rise 1%. Longer duration = more sensitivity = more risk and more reward. The 2022 bond rout was a duration story — long-dated US Treasuries fell 30%+ as yields surged.",
    related: ["yield", "bond"],
  },
  {
    slug: "bond",
    term: "Bond",
    termHi: "बॉन्ड",
    category: "bonds",
    short: "A loan made by you to a government or company, with a promise of regular interest and return of principal.",
    long: "Bonds are an IOU. You lend ₹100, get coupon payments every six months, and the ₹100 back at maturity. Government bonds are 'risk-free' (in their own currency); corporate bonds add credit risk and pay more for it.",
    related: ["yield", "g-sec", "duration", "coupon"],
  },
  {
    slug: "coupon",
    term: "Coupon",
    category: "bonds",
    short: "The fixed periodic interest payment a bond pays.",
    long: "A bond with face value ₹100 and 7% coupon pays ₹7 a year, usually in two ₹3.50 installments. The coupon never changes; the bond's price and yield do. When new bonds are issued at higher coupons, old low-coupon bonds fall in price.",
    related: ["bond", "yield"],
  },
  {
    slug: "qe",
    term: "QE (Quantitative Easing)",
    category: "rates-and-money",
    short: "Central bank buying bonds to push down long-term yields and inject liquidity.",
    long: "When policy rates hit zero, central banks turn to QE — they create money and buy government bonds. The Fed ran QE for most of 2008-2014 and again massively in 2020. Pushes asset prices up, weakens the currency.",
    related: ["qt", "fed", "liquidity"],
  },
  {
    slug: "qt",
    term: "QT (Quantitative Tightening)",
    category: "rates-and-money",
    short: "The reverse of QE — central bank shrinks its balance sheet.",
    long: "By letting bonds mature without reinvesting (or actively selling), the central bank withdraws liquidity. Headwind for risk assets. The Fed's QT program has been ongoing since mid-2022 at $60-95bn/month.",
    related: ["qe", "fed", "liquidity"],
  },
  {
    slug: "hawkish",
    term: "Hawkish",
    category: "rates-and-money",
    short: "Leaning toward higher interest rates / tighter policy.",
    long: "A hawkish RBI Governor is willing to hike rates and tolerate slower growth to crush inflation. Markets read every word of MPC statements for hawkish vs dovish drift.",
    related: ["dovish", "mpc"],
  },
  {
    slug: "dovish",
    term: "Dovish",
    category: "rates-and-money",
    short: "Leaning toward lower interest rates / easier policy.",
    long: "A dovish stance supports growth and employment, often at the cost of allowing inflation to run hotter. Equity markets generally rally on dovish surprises.",
    related: ["hawkish", "mpc"],
  },

  // -----------------------------------------------------------------------
  // Forex
  // -----------------------------------------------------------------------
  {
    slug: "usd-inr",
    term: "USD/INR",
    category: "forex",
    short: "How many rupees it takes to buy one US dollar.",
    long: "When USD/INR rises from 83 to 85, the rupee has weakened. Drivers: FII flows, oil prices (India is a big importer), US dollar strength, RBI intervention, current account balance. The RBI manages USD/INR more actively than most floating-rate central banks.",
    related: ["dxy", "rbi", "fii", "current-account"],
    example: "On 14 Nov 2024, USD/INR hit an all-time low (rupee at all-time low) of ~84.40 — driven by FII outflows and dollar strength after the US election.",
  },
  {
    slug: "dxy",
    term: "DXY (Dollar Index)",
    category: "forex",
    short: "The value of the US dollar measured against a basket of six major currencies.",
    long: "Components: euro (58%), yen (14%), pound (12%), Canadian dollar, Swedish krona, Swiss franc. When DXY rises, almost every other currency including the rupee weakens. DXY is one of the most powerful single signals for emerging market equity flows.",
    related: ["usd-inr", "carry-trade"],
  },
  {
    slug: "carry-trade",
    term: "Carry trade",
    category: "forex",
    short: "Borrowing in a low-yield currency to invest in a higher-yield currency or asset.",
    long: "For a decade, hedge funds borrowed yen at near 0% and bought everything from US tech to Mexican bonds. Carry works in calm markets; unwinds violently when volatility spikes. The August 2024 yen carry unwind shaved 12% off Nikkei in one day and rippled into Nifty.",
    related: ["yen", "boj"],
  },
  {
    slug: "yen",
    term: "Japanese yen (JPY)",
    category: "forex",
    short: "Japan's currency — historically the world's primary funding currency.",
    long: "BoJ kept rates at zero for two decades, making the yen the cheapest borrowing source on Earth. When BoJ finally hiked in 2024, the yen surged and carry traders scrambled to repay yen loans by selling everything else.",
    related: ["carry-trade", "boj"],
  },
  {
    slug: "boj",
    term: "BoJ (Bank of Japan)",
    category: "rates-and-money",
    short: "Japan's central bank.",
    long: "Pioneer of zero and negative interest rates. Held its policy rate at -0.1% for 8 years, finally hiking to +0.25% in July 2024. That second tiny hike helped trigger the carry-trade unwind.",
    related: ["yen", "carry-trade"],
  },
  {
    slug: "current-account",
    term: "Current account balance",
    category: "forex",
    short: "A country's net trade in goods, services, and income with the rest of the world.",
    long: "India runs a current account deficit (CAD) — we import more than we export, mostly because of oil. A widening CAD pressures the rupee. When oil falls or services exports rise, the CAD narrows and the rupee gets relief.",
    related: ["usd-inr", "trade-deficit"],
  },
  {
    slug: "forex-reserves",
    term: "Forex reserves",
    category: "forex",
    short: "Foreign currency, gold, and SDR holdings held by the RBI.",
    long: "Around $650 billion as of late 2024 — among the world's largest. The RBI uses these to defend the rupee, smooth FX volatility, and pay for imports if needed. Roughly 10 months of import cover.",
    related: ["rbi", "usd-inr"],
  },

  // -----------------------------------------------------------------------
  // Crude oil & commodities
  // -----------------------------------------------------------------------
  {
    slug: "brent",
    term: "Brent crude",
    category: "commodities",
    short: "The international oil benchmark, priced in USD per barrel.",
    long: "Brent is the price India effectively pays for imported oil. Sourced from North Sea fields, but it's the global reference. When Brent rises $10/barrel, India's annual oil import bill rises by ~$15 billion — straight pressure on the current account and rupee.",
    related: ["wti", "opec", "crude-oil"],
  },
  {
    slug: "wti",
    term: "WTI crude (West Texas Intermediate)",
    category: "commodities",
    short: "The US oil benchmark, priced in USD per barrel.",
    long: "WTI is lighter and sweeter than Brent. Usually trades a few dollars below Brent. Matters for US shale economics and as a second reference for the global oil tape.",
    related: ["brent", "opec"],
  },
  {
    slug: "opec",
    term: "OPEC / OPEC+",
    category: "commodities",
    short: "A cartel of major oil-producing countries that coordinates supply.",
    long: "OPEC (founded 1960) plus Russia and a few allies (OPEC+) sets production quotas roughly every six weeks. Cuts push prices up; increases push them down. Their meetings are calendar events for energy traders. Saudi Arabia and Russia are the swing producers.",
    related: ["brent", "wti", "crude-oil"],
  },
  {
    slug: "crude-oil",
    term: "Crude oil",
    termHi: "कच्चा तेल",
    category: "commodities",
    short: "Unrefined petroleum — the raw input for diesel, petrol, plastics, and chemicals.",
    long: "India imports ~85% of its crude. Every $10/barrel change in oil price moves the CAD by ~$15 billion and the rupee by ~50-70 paise on average. Oil is upstream of inflation, transport costs, and corporate margins.",
    related: ["brent", "opec", "current-account"],
  },
  {
    slug: "gold",
    term: "Gold",
    termHi: "सोना",
    category: "commodities",
    short: "A precious metal that acts as a store of value, especially in crises.",
    long: "Gold is the original anti-fiat asset. It rises when real yields fall, when the dollar weakens, and when there's geopolitical fear. India is the world's #2 consumer of gold (after China). Sovereign Gold Bonds (SGB) let you own gold without making charges and with a 2.5% coupon.",
    related: ["sgb", "real-yields", "safe-haven"],
  },
  {
    slug: "sgb",
    term: "SGB (Sovereign Gold Bond)",
    category: "commodities",
    short: "A government bond denominated in grams of gold, paying 2.5% annual interest.",
    long: "Issued by RBI in tranches. Tracks the gold price (so you get capital appreciation) plus 2.5% coupon. LTCG is exempt if held to maturity. Strictly better than holding physical gold for most investors. Listed on NSE/BSE for secondary trading.",
    related: ["gold"],
  },
  {
    slug: "real-yields",
    term: "Real yields",
    category: "bonds",
    short: "Bond yields after subtracting expected inflation.",
    long: "If the US 10Y is 4.5% and breakeven inflation is 2.3%, real yield is 2.2%. Gold and real yields move opposite — high real yields punish gold (you're paid to wait); negative real yields are gold's best friend (2020-2021).",
    related: ["yield", "gold", "inflation"],
  },
  {
    slug: "copper",
    term: "Copper",
    category: "commodities",
    short: "Industrial metal used in wiring, construction, EVs — and a key macro indicator.",
    long: "Called 'Dr. Copper' because it has a PhD in economics — copper demand leads global manufacturing cycles. Rising copper signals growth; falling copper warns of slowdown. China consumes ~55% of global copper.",
    related: ["industrial-metals"],
  },
  {
    slug: "industrial-metals",
    term: "Industrial metals",
    category: "commodities",
    short: "Copper, aluminium, nickel, zinc — used as inputs to manufacturing.",
    long: "Different metals have different stories. Copper is cyclical; aluminium tracks energy costs; nickel and lithium track EV demand. Indian companies like Hindalco, Vedanta, NMDC are direct plays.",
    related: ["copper"],
  },
  {
    slug: "safe-haven",
    term: "Safe haven",
    category: "intermarket",
    short: "An asset investors flock to in times of fear.",
    long: "Classic safe havens: US Treasuries, US dollar, gold, Swiss franc, Japanese yen. Bitcoin sometimes acts like a safe haven, more often like a leveraged tech stock. When equities sell off, watch where capital is hiding — that tells you what people are scared of.",
    related: ["gold", "risk-off", "us-10y"],
  },

  // -----------------------------------------------------------------------
  // Crypto
  // -----------------------------------------------------------------------
  {
    slug: "bitcoin",
    term: "Bitcoin (BTC)",
    category: "crypto",
    short: "The first and largest cryptocurrency, capped at 21 million units.",
    long: "Started 2009, post-financial-crisis. Originally a peer-to-peer payment idea; now mostly held as a macro asset. Correlates ~0.6 with Nasdaq — it acts more like a risk-on tech bet than digital gold most of the time.",
    related: ["ethereum", "halving"],
  },
  {
    slug: "ethereum",
    term: "Ethereum (ETH)",
    category: "crypto",
    short: "The second-largest crypto by market cap; a programmable smart contract platform.",
    long: "If Bitcoin is digital gold, Ethereum is digital infrastructure — most stablecoins, DeFi, and NFTs live on it. Switched to proof-of-stake in 2022. Highly correlated with Bitcoin but with more upside and downside.",
    related: ["bitcoin"],
  },
  {
    slug: "vda-tax",
    term: "VDA tax (India)",
    category: "taxes-india",
    short: "30% tax on crypto gains plus 1% TDS on every trade.",
    long: "Introduced in Budget 2022. VDA = Virtual Digital Asset. 30% flat rate, no offsetting losses against other income, 1% TDS on every transaction above ₹10,000 (₹50,000 for some). Has dramatically reduced Indian crypto trading volume.",
    related: ["bitcoin", "ltcg"],
  },
  {
    slug: "stablecoin",
    term: "Stablecoin",
    category: "crypto",
    short: "A crypto asset pegged to a fiat currency (usually USD).",
    long: "USDT (Tether) and USDC are the largest. Used as the trading pair and 'cash' of crypto markets. Theoretically backed 1:1 by dollars or T-bills. Practical risk: depegging events (USDC briefly fell to $0.87 during the SVB collapse in March 2023).",
    related: ["bitcoin", "svb"],
  },
  {
    slug: "halving",
    term: "Bitcoin halving",
    category: "crypto",
    short: "Every ~4 years, the new bitcoin issuance per block is cut in half.",
    long: "Hardcoded supply-side event. Past halvings (2012, 2016, 2020, 2024) have been followed by major bull runs over the next 12-18 months, though correlation isn't causation. Next halving in 2028.",
    related: ["bitcoin"],
  },

  // -----------------------------------------------------------------------
  // Intermarket & regimes
  // -----------------------------------------------------------------------
  {
    slug: "risk-off",
    term: "Risk-off",
    category: "intermarket",
    short: "A market environment where investors sell risky assets and seek safety.",
    long: "Risk-off shows up as: equities down, US dollar up, US Treasuries up (yields down), gold up, EM currencies down, junk bond spreads widening. India's USD/INR usually rises on risk-off days even if there's no India-specific news.",
    related: ["risk-on", "safe-haven", "vix"],
  },
  {
    slug: "risk-on",
    term: "Risk-on",
    category: "intermarket",
    short: "A market environment where investors embrace risk for higher returns.",
    long: "Opposite of risk-off. Equities up, dollar weaker, EM currencies stronger, junk spreads tighter, crypto and small caps lead. India tends to outperform during risk-on (FII inflows return).",
    related: ["risk-off"],
  },
  {
    slug: "business-cycle",
    term: "Business cycle",
    category: "intermarket",
    short: "The recurring pattern of expansion, slowdown, contraction, and recovery in an economy.",
    long: "Different sectors lead at different phases. Early cycle: cyclicals (banks, autos). Mid cycle: industrials. Late cycle: energy, materials. Recession: defensives (consumer staples, healthcare, utilities). Recovery: cyclicals again. Useful framework even when the cycle is messy.",
    related: ["four-quadrants"],
  },
  {
    slug: "four-quadrants",
    term: "Four quadrants framework",
    category: "intermarket",
    short: "A 2x2 grid of growth vs inflation that helps map which assets win in which regime.",
    long: "Rising growth + falling inflation = equities (best of all worlds, ~2017). Rising growth + rising inflation = commodities and value stocks (~2022). Falling growth + falling inflation = bonds (disinflation, ~2019). Falling growth + rising inflation = gold and cash (stagflation, 1970s).",
    related: ["business-cycle", "stagflation"],
  },
  {
    slug: "stagflation",
    term: "Stagflation",
    category: "intermarket",
    short: "An economy with stagnant growth and high inflation simultaneously.",
    long: "The nightmare regime. 1970s US under oil shocks. Hard for central banks: hiking kills growth further, cutting fuels inflation. Equities and bonds both lose; only commodities and gold tend to work. Brief stagflation worries hit markets in mid-2022.",
    related: ["four-quadrants", "inflation"],
  },
  {
    slug: "recession",
    term: "Recession",
    termHi: "मंदी",
    category: "intermarket",
    short: "Two consecutive quarters of negative GDP growth (rough rule of thumb).",
    long: "Officially in the US, defined by NBER, not the rule above. Recessions usually involve rising unemployment, falling corporate profits, equity drawdowns of 30%+, and credit spread blowouts. India has not had a technical recession since 1980 (COVID being a near-miss).",
    related: ["yield-curve", "business-cycle"],
  },
  {
    slug: "soft-landing",
    term: "Soft landing",
    category: "intermarket",
    short: "When a central bank cools inflation without causing a recession.",
    long: "Rare. The Fed managed it in 1994-95 and arguably 2023-24. Hard landing = recession; no landing = inflation stays high. Markets celebrate soft landings.",
    related: ["recession", "fed"],
  },

  // -----------------------------------------------------------------------
  // Indicators
  // -----------------------------------------------------------------------
  {
    slug: "gdp",
    term: "GDP (Gross Domestic Product)",
    termHi: "सकल घरेलू उत्पाद",
    category: "rates-and-money",
    short: "The total value of goods and services produced in a country per year.",
    long: "India's GDP is about $3.7 trillion (FY24). Real GDP growth (after inflation) of 6.5-7% is the current trend. GDP releases move bond markets more than equities; what really matters for stocks is corporate earnings, which loosely follow nominal GDP.",
    related: ["inflation", "real-return"],
  },
  {
    slug: "pmi",
    term: "PMI (Purchasing Managers' Index)",
    category: "rates-and-money",
    short: "A survey-based number that signals manufacturing/services expansion or contraction.",
    long: "Above 50 = expansion. Below 50 = contraction. Released monthly. The first hard read on each new month, often released before GDP. India's PMI is published by S&P Global; the US ISM PMI is closely watched globally.",
    related: ["gdp"],
  },
  {
    slug: "nfp",
    term: "NFP (US Non-Farm Payrolls)",
    category: "rates-and-money",
    short: "The monthly US jobs report — net jobs added/lost outside farming.",
    long: "Released first Friday of each month. Headline number, unemployment rate, and average hourly earnings all move markets simultaneously. Strong NFP = Fed less likely to cut = bonds down, dollar up, Nifty often down. The biggest scheduled macro event in any given month.",
    related: ["fed", "fomc"],
  },
  {
    slug: "fiscal-deficit",
    term: "Fiscal deficit",
    termHi: "राजकोषीय घाटा",
    category: "rates-and-money",
    short: "Government spending minus its tax revenue, expressed as a percentage of GDP.",
    long: "India's fiscal deficit is around 4.9% of GDP for FY25, glide-pathing toward 4.5%. Wider deficits mean more government borrowing, which raises G-Sec yields. Budget day announcements drive bond markets harder than equity markets.",
    related: ["g-sec", "yield"],
  },
  {
    slug: "trade-deficit",
    term: "Trade deficit",
    category: "rates-and-money",
    short: "When a country imports more than it exports.",
    long: "India runs a goods trade deficit (driven by oil and gold imports) offset partly by services exports (IT). Widening trade deficits pressure the rupee. Monthly trade data is released by the Commerce Ministry.",
    related: ["current-account", "usd-inr"],
  },

  // -----------------------------------------------------------------------
  // Taxes (India)
  // -----------------------------------------------------------------------
  {
    slug: "ltcg",
    term: "LTCG (Long-Term Capital Gains)",
    category: "taxes-india",
    short: "Tax on gains from selling listed shares held >1 year — 12.5% above ₹1.25 lakh.",
    long: "Rules changed in Budget 2024: LTCG on listed equity is now 12.5% (was 10%) with a ₹1.25 lakh annual exemption. Below that threshold, gains are tax-free. Holding period for listed shares is 1 year; for unlisted shares and most other assets, it's 24 months.",
    related: ["stcg", "stt", "vda-tax"],
  },
  {
    slug: "stcg",
    term: "STCG (Short-Term Capital Gains)",
    category: "taxes-india",
    short: "Tax on gains from selling listed shares held ≤1 year — 20% flat.",
    long: "Budget 2024 raised STCG on listed equity from 15% to 20%. Encourages longer holding periods. F&O income is taxed differently — as business income at your slab rate.",
    related: ["ltcg", "stt"],
  },
  {
    slug: "stt",
    term: "STT (Securities Transaction Tax)",
    category: "taxes-india",
    short: "A small tax on every equity trade — built into the price you pay.",
    long: "0.1% on delivery buy and sell each. F&O STT is lower but on a much larger notional. Cannot be claimed back; it's the cost of trading on Indian exchanges. Budget 2024 raised STT on F&O materially.",
    related: ["t-plus-1", "ltcg"],
  },
  {
    slug: "section-80c",
    term: "Section 80C",
    category: "taxes-india",
    short: "Income tax deduction of up to ₹1.5 lakh for specified investments and expenses.",
    long: "ELSS, EPF, PPF, NSC, life insurance premium, home loan principal — all eligible. Useful only if you're on the old tax regime; the new regime has no 80C deduction. Tax saved here directly improves your real return.",
    related: ["elss"],
  },
  {
    slug: "elss",
    term: "ELSS (Equity Linked Savings Scheme)",
    category: "taxes-india",
    short: "An equity mutual fund category with 3-year lock-in, eligible for Section 80C.",
    long: "Shortest lock-in among 80C options. Equity returns over 3+ years generally beat PPF or NSC. Caveat: only works for the old tax regime, and 80C cap is ₹1.5 lakh.",
    related: ["section-80c", "ltcg"],
  },

  // -----------------------------------------------------------------------
  // Misc / events
  // -----------------------------------------------------------------------
  {
    slug: "svb",
    term: "SVB (Silicon Valley Bank)",
    category: "intermarket",
    short: "Mid-sized US bank that collapsed in March 2023 from a duration mismatch.",
    long: "SVB held long-duration Treasuries funded by short-duration deposits. When the Fed hiked, the bonds lost value. When startups withdrew deposits to cover burn, SVB had to sell bonds at a loss. Run + collapse + emergency Fed liquidity. Triggered USDC depeg and a regional bank crisis.",
    related: ["duration", "fed", "stablecoin"],
  },
  {
    slug: "volcker-shock",
    term: "Volcker shock",
    category: "intermarket",
    short: "Fed Chair Paul Volcker hiked US rates to 20% in 1980 to crush inflation.",
    long: "Successfully killed double-digit inflation but caused a deep recession and crushed emerging markets globally. The historical playbook for 'whatever it takes' tight policy. Often referenced when Fed officials want to signal seriousness.",
    related: ["fed", "inflation", "recession"],
  },
  {
    slug: "hindenburg",
    term: "Hindenburg Research",
    category: "indian-equities",
    short: "US short-selling research firm that publishes critical reports on companies.",
    long: "Famous for the January 2023 Adani Group report alleging stock manipulation and accounting fraud. Adani Group lost over $150 billion in market cap in weeks. Hindenburg is short the stocks it reports on — incentive alignment to watch carefully.",
    related: ["short-selling"],
  },
  {
    slug: "short-selling",
    term: "Short selling",
    category: "indian-equities",
    short: "Selling a borrowed share, hoping to buy it back later at a lower price.",
    long: "If TCS is ₹4,200 and you short it, you sell at ₹4,200 and pocket the cash. If TCS falls to ₹3,800, you buy back, return the share, and keep ₹400. Losses are theoretically unlimited (a stock can rise indefinitely). In India, intraday shorts are common; overnight shorts require derivatives.",
    related: ["fno", "leverage"],
  },
  {
    slug: "demonetisation",
    term: "Demonetisation",
    category: "intermarket",
    short: "November 2016 invalidation of ₹500 and ₹1,000 notes in India.",
    long: "Announced on 8 November 2016 evening; ~86% of currency value invalidated overnight. Goal was black money and counterfeit suppression. Caused short-term cash crunch and consumption slowdown. Pushed Indian savings into financial assets — a long tailwind for mutual funds.",
    related: [],
  },

  // -----------------------------------------------------------------------
  // Additional terms (Phase 2 expansion)
  // -----------------------------------------------------------------------
  {
    slug: "m2",
    term: "M2 money supply",
    category: "rates-and-money",
    short: "A broad measure of US money supply — cash + checkable deposits + savings + retail money market funds.",
    long: "US M2 grew ~25% from March 2020 to early 2022 — massive monetary expansion. M2 growth is a leading indicator of inflation (rough 18-24 month lag). M2 contracted in 2022-23 for the first time since the 1940s.",
    related: ["qe", "qt", "inflation"],
  },
  {
    slug: "breakeven",
    term: "Breakeven inflation rate",
    category: "bonds",
    short: "Market-implied inflation expectation derived from TIPS vs nominal Treasury yields.",
    long: "If nominal 10Y is 4.5% and TIPS 10Y real yield is 2%, breakeven inflation = 2.5%. Market's collective inflation forecast over 10 years. Trades real-time, faster than economist forecasts.",
    related: ["real-yields", "cpi", "inflation"],
  },
  {
    slug: "rrp",
    term: "Reverse Repo facility (RRP)",
    category: "rates-and-money",
    short: "Fed facility where banks and money funds park overnight cash at the Fed.",
    long: "Peaked at $2.5 trillion in 2022. Now around $200B. Money 'parked' at RRP is liquidity that's not in the broader economy. Draining RRP returns liquidity to the system — positive for risk assets.",
    related: ["fed", "qt"],
  },
  {
    slug: "sahm-rule",
    term: "Sahm rule",
    category: "intermarket",
    short: "A recession indicator that triggers when the 3-month moving average of US unemployment rises 0.5+ percentage points within 12 months.",
    long: "Created by economist Claudia Sahm. Historically perfect track record from 1960s. Triggered in August 2024 NFP. Subsequent recession arrival is being debated.",
    related: ["nfp", "recession"],
  },
  {
    slug: "ism",
    term: "ISM PMI",
    category: "rates-and-money",
    short: "US Institute for Supply Management Purchasing Managers' Index — equivalent of PMI for the US.",
    long: "Above 50 = expansion. Major data point released first business day of each month. ISM Manufacturing below 47 has predicted US recessions historically. Watched globally as leading indicator.",
    related: ["pmi", "recession"],
  },
  {
    slug: "pce",
    term: "PCE inflation",
    category: "rates-and-money",
    short: "Personal Consumption Expenditures inflation — Fed's preferred inflation measure.",
    long: "Differs from CPI in basket weights and methodology. Fed officially targets 2% PCE (vs 4% Indian CPI). Released end of month for previous month. Core PCE strips food and energy like core CPI.",
    related: ["cpi", "core-cpi", "fed"],
  },
  {
    slug: "fcnr",
    term: "FCNR (Foreign Currency Non-Resident) deposit",
    category: "forex",
    short: "Dollar-denominated bank deposit for NRIs in India.",
    long: "NRI can hold deposits in USD, GBP, EUR, AUD, CAD, JPY, SGD. Interest tax-free in India. No exchange risk for depositor. Useful tool for returning NRIs to maintain dollar exposure.",
    related: ["nre", "usd-inr"],
  },
  {
    slug: "nre",
    term: "NRE (Non-Resident External) account",
    category: "forex",
    short: "Rupee-denominated NRI account; principal and interest fully repatriable.",
    long: "Interest tax-free in India. Useful for NRIs earning abroad. Money sent into NRE from abroad can be converted back to USD anytime and remitted out without restriction.",
    related: ["fcnr", "usd-inr"],
  },
  {
    slug: "tcs-lrs",
    term: "TCS on LRS",
    category: "taxes-india",
    short: "20% Tax Collected at Source on LRS remittances above ₹7 lakh per year.",
    long: "Introduced October 2023. Applies to overseas remittances for investments, education, travel, etc. TCS is adjusted against your tax liability when you file returns — refundable if excess. Real cash flow drag.",
    related: ["ltcg"],
  },
  {
    slug: "gst",
    term: "GST (Goods and Services Tax)",
    category: "taxes-india",
    short: "India's unified indirect tax replacing pre-2017 state-level VATs.",
    long: "Slabs: 0%, 5%, 12%, 18%, 28%. Most listed company products in 18% slab. GST collections (~₹1.5+ lakh cr/month) are a key leading indicator of economic activity.",
    related: [],
  },
  {
    slug: "promoter",
    term: "Promoter",
    termHi: "प्रवर्तक",
    category: "indian-equities",
    short: "Founders or controlling shareholders of an Indian listed company.",
    long: "Promoters typically own 30-70%+ of Indian listed companies. Their pledging behavior, transaction history, and credibility are key risk factors. SEBI tracks promoter shareholding changes closely.",
    related: ["pledge"],
  },
  {
    slug: "pledge",
    term: "Promoter pledge",
    category: "indian-equities",
    short: "When promoter pledges shares as collateral for personal loans.",
    long: "If pledged shares' value falls below loan collateral requirement, lender can force-sell them. This creates compound selling pressure during drawdowns. >20% promoter pledge is a major red flag.",
    related: ["promoter"],
  },
  {
    slug: "ipo",
    term: "IPO (Initial Public Offering)",
    category: "indian-equities",
    short: "First-time public sale of a company's shares.",
    long: "Indian IPO market is large but quality is mixed. 60-70% of IPOs trade below issue price 3 years later. Pre-IPO hype is sales communication; wait 6-12 months post-listing before evaluating.",
    related: ["fpo"],
  },
  {
    slug: "fpo",
    term: "FPO (Follow-on Public Offering)",
    category: "indian-equities",
    short: "Additional shares offered by an already-listed company.",
    long: "Used to raise capital after the IPO. Adani Enterprises FPO of January 2023 was withdrawn after Hindenburg report; LIC FPO was rumored multiple times. Often signals capital needs.",
    related: ["ipo", "dilution"],
  },
  {
    slug: "dilution",
    term: "Dilution",
    category: "indian-equities",
    short: "When new shares are issued, reducing each existing shareholder's percentage ownership.",
    long: "Common in FPOs, QIPs, and ESOP grants. 5-10% dilution can be a meaningful overhang for stock price. Watch promoter dilutions especially — they reduce future per-share earnings power.",
    related: ["fpo", "qip"],
  },
  {
    slug: "qip",
    term: "QIP (Qualified Institutional Placement)",
    category: "indian-equities",
    short: "Way for listed companies to raise capital from institutional investors only.",
    long: "Faster than FPO, no retail involvement. Used by banks, infrastructure, and corporate companies to raise growth capital. Dilutive but typically at premium to market.",
    related: ["dilution", "fpo"],
  },
  {
    slug: "anchor",
    term: "Anchor investor",
    category: "indian-equities",
    short: "Institutional investor that subscribes to an IPO 1 day before retail subscription opens.",
    long: "30-day lock-in. Signals institutional confidence to retail subscribers. Often global hedge funds and mutual funds. Anchor demand quality is one tell of IPO quality.",
    related: ["ipo"],
  },
  {
    slug: "book-building",
    term: "Book building",
    category: "indian-equities",
    short: "Price-discovery mechanism for IPOs where investors bid within a price band.",
    long: "Indian IPOs are typically book-built. Price band is usually ₹X to ₹X+5% (small band). Heavy oversubscription often pushes final pricing to upper end of band.",
    related: ["ipo"],
  },
  {
    slug: "circuit",
    term: "Circuit (upper/lower)",
    category: "risk",
    short: "Daily price band limit beyond which trading halts in a stock.",
    long: "Indian stocks have 2%, 5%, 10%, 20% circuits depending on category. Lower circuit = price drop limit hit, no buyers, you can't sell. Upper circuit = price rise limit, no sellers, you can't buy. Index-wide circuits (10%, 15%, 20%) halt entire markets.",
    related: ["circuit-breaker"],
  },
  {
    slug: "earnings-yield",
    term: "Earnings yield",
    category: "indian-equities",
    short: "Inverse of P/E — earnings per share divided by stock price, expressed as percentage.",
    long: "E/P. If P/E is 20, earnings yield is 5%. Comparable to bond yields. Earnings yield > bond yield = equity attractive; earnings yield < bond yield = bonds attractive. Indian Nifty earnings yield currently ~4-5%.",
    related: ["pe-ratio", "yield"],
  },
  {
    slug: "dpr",
    term: "DPR (Debt-to-Equity ratio)",
    category: "indian-equities",
    short: "A company's total debt divided by shareholders' equity.",
    long: "Lower = less leveraged = safer. >2 is high; >5 is very high. Bank balance sheets are excluded from this metric (banks intrinsically leverage). Adani Group's debt-equity caused concerns leading into Hindenburg report.",
    related: ["leverage"],
  },
  {
    slug: "free-float",
    term: "Free float",
    category: "indian-equities",
    short: "Shares actually available for public trading, excluding promoter and government holdings.",
    long: "Nifty 50 uses free-float market cap, not total market cap. A government-heavy stock like Coal India has much smaller free-float than total market cap. Affects index inclusion eligibility and weights.",
    related: ["market-cap"],
  },
  {
    slug: "circuit-filter",
    term: "Circuit filter",
    category: "risk",
    short: "Pre-set price band limits that trigger circuit halts.",
    long: "Different from circuit breaker. Filter is the band itself; breaker is the halt. NSE sets these based on stock liquidity, market cap, group classification. T2T (trade-to-trade) segment has 5% filter.",
    related: ["circuit", "circuit-breaker"],
  },
  {
    slug: "mcap",
    term: "Mcap",
    category: "indian-equities",
    short: "Shorthand for market capitalization. Same as market-cap.",
    long: "Used interchangeably with market-cap. ₹X crore mcap, ₹X lakh crore mcap. Mcap rankings used for SEBI's large/mid/small cap classification.",
    related: ["market-cap"],
  },
  {
    slug: "atr",
    term: "ATR (Average True Range)",
    category: "risk",
    short: "Technical indicator measuring price volatility over a period.",
    long: "Used for sizing stops and positions. Typical Nifty daily ATR is 200-400 points. Stocks with higher ATR are more volatile per unit. Useful for risk management in active trading.",
    related: ["volatility"],
  },
  {
    slug: "elss-detail",
    term: "ELSS (Equity Linked Savings Scheme)",
    category: "taxes-india",
    short: "Equity mutual fund category with 3-year lock-in, eligible for Section 80C deduction.",
    long: "Shortest lock-in among 80C options (vs PPF 15-year). Equity returns generally beat PPF/NSC over 3+ years. Caveat: only works for old tax regime; 80C cap ₹1.5 lakh.",
    related: ["section-80c"],
  },
  {
    slug: "ppf",
    term: "PPF (Public Provident Fund)",
    category: "taxes-india",
    short: "Government-backed savings scheme; tax-free interest, principal, and maturity.",
    long: "15-year lock-in. Annual contribution cap ₹1.5 lakh. Current interest rate ~7.1%. Triple tax-exempt (EEE) — contributions deductible, interest tax-free, withdrawals tax-free. Best 'fixed income' for high tax bracket Indians.",
    related: ["section-80c", "epf"],
  },
  {
    slug: "epf",
    term: "EPF (Employees' Provident Fund)",
    category: "taxes-india",
    short: "Mandatory salary-linked retirement savings for Indian salaried employees.",
    long: "Contributions: 12% of basic salary from employee + 12% from employer. Interest currently 8.25%. Tax-free interest and maturity. Massive base for Indian household savings (~₹16 lakh crore total corpus).",
    related: ["section-80c", "ppf"],
  },
  {
    slug: "nps",
    term: "NPS (National Pension System)",
    category: "taxes-india",
    short: "Government-backed pension scheme with additional ₹50,000 tax deduction beyond 80C.",
    long: "Section 80CCD(1B) gives ₹50k deduction over and above 80C's ₹1.5L. Partial tax-free withdrawal at 60 (60% lump sum, 40% must buy annuity). Underutilized — many Indians should add ₹50k annual NPS contribution.",
    related: ["section-80c", "ppf"],
  },
  {
    slug: "intrinsic-value",
    term: "Intrinsic value",
    category: "indian-equities",
    short: "An estimate of what a security is fundamentally worth based on cash flows.",
    long: "From valuation models like DCF (Discounted Cash Flow). Price oscillates around intrinsic value over time. Buying when price < intrinsic value, selling when price > intrinsic value, is the value-investing approach.",
    related: ["valuation", "pe-ratio"],
  },
  {
    slug: "valuation-multiple",
    term: "Valuation multiple",
    category: "indian-equities",
    short: "Ratio used to compare price to a fundamental metric (P/E, P/B, EV/EBITDA, P/S).",
    long: "Different multiples for different sectors. Banks use P/B; IT uses P/E; commodity producers use EV/EBITDA; loss-making growth companies use price-to-sales (P/S).",
    related: ["pe-ratio", "pb-ratio"],
  },
  {
    slug: "moat",
    term: "Economic moat",
    category: "indian-equities",
    short: "A company's durable competitive advantage that protects long-term profits.",
    long: "Moats: brand (Asian Paints), network effects (NSE), patents (pharma originators), regulatory (banks), cost advantage (Reliance refining). Stocks with deep moats sustainably compound. Term popularized by Warren Buffett.",
    related: ["valuation", "compounding"],
  },
  {
    slug: "compounding",
    term: "Compounding",
    category: "foundations",
    short: "Generating returns on previously earned returns. The math that makes long-term wealth.",
    long: "At 12% CAGR, money doubles every 6 years. ₹1 lakh becomes ₹3 lakh in 10 years, ₹10 lakh in 20 years, ₹30 lakh in 30 years. Time is the most important variable in compounding. Albert Einstein famously called it 'the most powerful force in the universe'.",
    related: ["sip"],
  },
  {
    slug: "ipo-anchor",
    term: "Anchor lock-in",
    category: "indian-equities",
    short: "30-day lock-in period for anchor investors after IPO.",
    long: "Anchor investors who subscribe pre-IPO must hold for 30 days post-listing. Day 31 sometimes sees pressure as anchors sell. Worth watching as a tactical signal for IPO holders.",
    related: ["anchor", "ipo"],
  },
  {
    slug: "stt-detail",
    term: "STT on options",
    category: "taxes-india",
    short: "Securities Transaction Tax on options trades; raised materially in Budget 2024.",
    long: "Budget 2024 hiked STT on sell-side of options from 0.0625% to 0.10% on premium. Effective additional cost for active F&O traders. Combined with other rules (lot size increases, weekly expiry cuts), made F&O trading materially costlier.",
    related: ["stt", "fno"],
  },
  {
    slug: "windfall-tax",
    term: "Windfall tax",
    category: "taxes-india",
    short: "Special tax on excess profits during commodity price spikes.",
    long: "Indian government imposes windfall taxes on upstream oil companies (ONGC, Reliance) and refiners when oil prices stay elevated. Rates adjusted fortnightly. Caps shareholder upside during oil rallies.",
    related: ["crude-oil"],
  },
  {
    slug: "fdi",
    term: "FDI (Foreign Direct Investment)",
    category: "forex",
    short: "Long-term foreign investment in Indian businesses, distinct from portfolio (FPI/FII).",
    long: "Major source of dollar inflows. Includes foreign companies setting up Indian subsidiaries (Apple manufacturing, Foxconn) and acquisitions. ~$70B/year recently. Sticky money — doesn't flow out on risk-off like FIIs do.",
    related: ["fii", "current-account"],
  },
  {
    slug: "remittance",
    term: "Remittance",
    category: "forex",
    short: "Money sent home by Indians working abroad.",
    long: "India is the world's largest remittance recipient — ~$120B+/year. Major dollar inflow that doesn't reverse during crises. Structural cushion for Indian current account. Top source countries: UAE, US, Saudi Arabia, Kuwait, UK.",
    related: ["current-account", "usd-inr"],
  },
  {
    slug: "blocking",
    term: "Promoter pledging block-up",
    category: "indian-equities",
    short: "When promoter pledging suddenly increases significantly.",
    long: "If promoter pledges rise from 20% to 50% in a quarter, it signals financial stress at the promoter level. Watch for this in red-flag stocks. Often precedes operational issues.",
    related: ["pledge", "promoter"],
  },
  {
    slug: "esg",
    term: "ESG (Environmental, Social, Governance)",
    category: "intermarket",
    short: "Investment framework emphasizing sustainability and governance metrics.",
    long: "Many global funds have ESG mandates that affect Indian stock weights — coal-heavy companies (Coal India) and high-carbon names sometimes excluded by ESG funds. Adani Group faced ESG concerns post-Hindenburg report.",
    related: [],
  },
  {
    slug: "shareholding-pattern",
    term: "Shareholding pattern",
    category: "indian-equities",
    short: "Breakdown of who owns a listed company's shares — promoter, FII, DII, retail, etc.",
    long: "Published quarterly. SEBI mandates this disclosure. Useful to track FII/DII trends in specific stocks. Changes can be material — a sudden jump in promoter holding or FII reduction signals important shifts.",
    related: ["fii", "dii", "promoter"],
  },
  {
    slug: "buyback",
    term: "Share buyback",
    category: "indian-equities",
    short: "When a company repurchases its own shares from the market.",
    long: "Returns cash to shareholders, reduces share count (boosting EPS). Indian tax: now treated as deemed dividend at slab rate (Budget 2024 change). Companies like TCS, Infosys regularly buy back.",
    related: [],
  },
  {
    slug: "spread",
    term: "Spread",
    category: "foundations",
    short: "Generic term for the difference between two prices or rates.",
    long: "Bid-ask spread (market microstructure); credit spread (corporate bond yield over G-Sec); rate spread (Indian repo vs Fed funds); Brent-WTI spread. Context-dependent.",
    related: ["bid-ask"],
  },
  {
    slug: "fairlie",
    term: "Free-float methodology",
    category: "indian-equities",
    short: "Index construction approach using only publicly tradeable shares.",
    long: "Nifty 50 uses free-float methodology. Excludes promoter and government holdings. Different from earlier full market cap weighting. Better represents actual investor positioning.",
    related: ["free-float", "market-cap"],
  },
];

export function getTerm(slug: string): GlossaryTerm | undefined {
  return GLOSSARY.find((g) => g.slug === slug);
}

export function searchGlossary(query: string): GlossaryTerm[] {
  const q = query.trim().toLowerCase();
  if (!q) return GLOSSARY;
  return GLOSSARY.filter((g) => {
    return (
      g.term.toLowerCase().includes(q) ||
      g.slug.toLowerCase().includes(q) ||
      g.short.toLowerCase().includes(q) ||
      (g.termHi && g.termHi.includes(query)) ||
      (g.long && g.long.toLowerCase().includes(q))
    );
  });
}
